### ISSUE TITLE
delete InformationSheet.js

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#121]
**What's wrong**
InformationSheet.js is unlinked and a legacy component

**What done looks like**
InformationSheet.js is deleted and not a route in index.js

**Where the changes need to be made**
InformationSheet.js, index.js

**Comment by dearpriyankasa** [comment]
Related PR: https://github.com/precision-sustainable-ag/dst-selector/pull/123
