### ISSUE TITLE
sidebar dropdown broken

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#141]
**What's wrong**
clicking cover crop properties doesn't activate the dropdown

**Comment by Adamws33** [comment]
I believe this is working properly.  the reason the options are not available is a plant Hardiness zone was not yet selected.  I believe this was written like this intentionally.  The covercrop-selector.org site does not load with a location set so there is not a plant hardiness zone selected.  once a zone is selected the options appear.
