### ISSUE TITLE
proposal: make my cover crop list always visible

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#215]
**What's wrong**
user feedback said that because the cover crop list isn't visible at first it was confusing to find it after they had added crops to it. should we make it visible from the start?

**Comment by Adamws33** [comment]
I think the tab should always be there and the addition of the number in the right corner is enough to signify its in use or not.

**Comment by mikahpinegar** [comment]
yeah i agree
