### ISSUE TITLE
info sheet gets all messed up on thinner windows

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#219]
**What's wrong**
![wonky](https://user-images.githubusercontent.com/55995241/203361683-72371045-92d8-4946-9af4-c6cbd8223316.PNG)

**What done looks like**
goals should stay aligned at different widths. not sure best solution to implement this

**Where the changes need to be made**
info sheet

**Comment by Adamws33** [comment]
@mikahpinegar Lets discuss monday how we want this to look.  i have some ideas but some of the changes i think we will need to make to make the info vs. topic clear on a thin screen might have a bigger impact than just this section.
