### ISSUE TITLE
soil drainage gets messed up on smaller screens in info sheet

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#220]
**What's wrong**
![drainage](https://user-images.githubusercontent.com/55995241/203362088-3d3615e3-36f6-4c2f-a6cc-6b26f8ee8ec3.PNG)

**What done looks like**
the vertical line should stay straight on different sized screens or another method of showing the data should be used

**Where the changes need to be made**
info sheet

**Comment by Adamws33** [comment]
@ssharm1524  to resolve this we want to update the information sheet to be just a single column on smaller screens.  we can chat about this too so i can screen share and show you at what point this should shift to single column.
