### ISSUE TITLE
suggest areas that can be improved in the project

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#23]
we want to rearchitect how the goal ratings are stored. currently the experts edit in airtable and then we pull that info into a mongo db and convert the mongo collections into json objects and then access it directly. our thought process for going forward is to do the following
- stop using airtable because there will not be lots of changes in the future
- migrate the existing data in airtable into a postgres db 
- build an api around serving the ratings and information sheets
- store the cover crop images in blob storage and maybe build an api around that
- update the front end to use these apis
- remove all the json objects that store the ratings/info sheets from the repo
- remove all the images from the repo

once you have a feel for how things are architected we would like to get your input on the above plan and get your suggestions for impprovement

**Comment by drewlearns** [comment]
Made multiple suggestions to the confluence and added some notes to the README.md though it still needs some love by a seasoned veteran or two.
