### ISSUE TITLE
WCCC Implementation Requirement - Remove soil drainage from core filtering logic

### ISSUE THREAD

**Issue by julietnpn** [precision-sustainable-ag/dst-selector#237]
**What's wrong**
For the NE and S, the tool is poised to cull the list of cover crop candidates based on soil drainage (in addition to goals). The WCCC wants to eliminate that functionality. They want to show the entire list of cover crop candidates with only the goals culling the list.

**What done looks like**
This needs to be figured out -- this could have implications on how the wizard works, and may require that soil drainage be placed in the filter bar with some kind of toggle that allows you to "filter for my soil drainage". They are open to this being one of the filters in the filter bar, just not a culling mechanism.

**Comment by julietnpn** [comment]
Quick update: This remains true in general, but there are now some regional exceptions a-brewing. See #546

**Comment by mikahpinegar** [comment]
@Adamws33 let's add a filter to the sidebar that is a yes/no option for filtering on soil drainage. by default, SCCC,NECCC,MCCC will be set to yes, and WCCC will be set to no. the user can then change this if desired

**Comment by Diksha-Maurya** [comment]
@Adamws33 As per our conversation, I will position the 'Clear Filter' to the center width fixed height so that other filters remain fixed at their position.
