### ISSUE TITLE
Remove Drew Karriker from all the repositories

### ISSUE THREAD

**Issue by drewlearns** [precision-sustainable-ag/dst-selector#240]

**Comment by mikahpinegar** [comment]
just looked through every repo i could think of and don't see you in any. i removed you from the whole org a while back. are you still getting notifications? if you tell me which repos you're in i can remove you but i don't see any. maybe you have them starred?

**Comment by mikahpinegar** [comment]
are you talking about something other than being a collaborator on repos? you're still a member for the azure pipelines. i can remove you from there if you want

**Comment by mikahpinegar** [comment]
just kidding i actually can't remove you from the psa-dst azure devops project because you're the owner
