### ISSUE TITLE
Update Selector to be ready for other councils. 

### ISSUE THREAD

**Issue by Adamws33** [precision-sustainable-ag/dst-selector#261]
**What's wrong**
move the first tab to be the selector tab
update first screen to make NECCC info
make logo dynamic based on council 
use zone API to build zone dropdown list based on council. 
create drop down for Midwest for counties. 
make map dynamic based on council.  

**What done looks like**
the application will start on selector with a state drop down and no NECCC info. or logo.  the zone list, counties, and map need to appear based on the selected council.  

**Where the changes need to be made**

**Comment by mikahpinegar** [comment]
also the calendar view should be the default instead of the list view for the species selector
