### ISSUE TITLE
Proposed feature: Clickable-to-sort columns on results page

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/dst-selector#283]
**What's wrong**
- The column headers look like clickable buttons, so you expect them to sort on-click.
- Currently if you click the bar above the Goals headers, there's a sorting icon that toggles visually, but does nothing.

> <img width="353" alt="Screen Shot 2023-02-10 at 14 17 10" src="https://user-images.githubusercontent.com/13338560/218178542-ef4dda45-91e4-46e8-85eb-bc4642ebc6d4.png">
> <img width="353" alt="Screen Shot 2023-02-10 at 14 16 48" src="https://user-images.githubusercontent.com/13338560/218178543-5c66d09d-a1b5-47eb-9823-42cb8a616f5d.png">

**What done looks like**
- Make Goals 1-3, and Name always sortable.
- If previous crop is filled in, then the planting window can be sorted by the following logic:
  - Crops that are in their "green" planting window  (unclear what this is called in the API) at the time of the previous cash crop harvest date come first. 
  - Then the crops that are in their "yellow" planting window would come next. 
  - Then the earliest date of a new planting window would come next (wrapping around from December to January as needed).

**Comment by brianwdavis** [comment]
After thinking about it some more, I think sorting the dates can be easier. Just choose the first date returned by the API, even if there's a multi-chunk planting window, and sort by that.

**Comment by mikahpinegar** [comment]
sort descending by the last day of reliable establishment when the user clicks `Planting Window`
