### ISSUE TITLE
Chip styling on mobile is inconsistent 

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/dst-selector#286]
**What's wrong**
- Firefox Mobile on a Pixel 6a screen size
- Chip borders are clipped and inconsistent weights throughout application 
- Full size as loaded vs zoomed in:
![Screenshot_20230214-110315](https://user-images.githubusercontent.com/13338560/218807803-76094e9d-a90c-44ae-a9ea-3e5b2dd321b2.png)
![Screenshot_20230214-110329](https://user-images.githubusercontent.com/13338560/218807825-34092650-4d2d-4828-bea6-0d80c27790b9.png)

**Comment by mikahpinegar** [comment]
try increasing the size of the chips on mobile. when i zoom in they look fine
