### ISSUE TITLE
Logo header doesn't style correctly on iPad size screens

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/dst-selector#288]
**What's wrong**
- In both Chrome and Safari on an iPad Air 2, the application header appears as below:

|||
| --- |  --- |
| ![PXL_20230216_162553063](https://user-images.githubusercontent.com/13338560/219433517-08878ac3-20f5-4ef3-95b9-d0f9b760ac59.jpg) | ![PXL_20230216_162606428](https://user-images.githubusercontent.com/13338560/219433547-e3c268ab-5ac4-457c-b07e-cf7b9ccb2119.jpg) |

**What done looks like**
- Show unclipped logo in header

**Comment by mikahpinegar** [comment]
add logos for each council, i will attach them to this issue

**Comment by mikahpinegar** [comment]
![neccc_logo](https://user-images.githubusercontent.com/55995241/233186944-ca99e37c-d208-4fa7-8c8b-6298a6f3d55e.jpg)
<img width="176" alt="mccc_logo" src="https://user-images.githubusercontent.com/55995241/233186946-74fe7137-7f65-43f5-a223-393d1b2d3328.PNG">
![sccc-logo-oval](https://user-images.githubusercontent.com/55995241/233186950-18b474d0-666f-454c-9e99-238bedb50b0b.png)
