### ISSUE TITLE
Should the analytics popup remember users?

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/dst-selector#290]
From a user:
> Every time I go to https://covercrop-selector.org/ it asks me to accept or decline Google Analytics and I decline. And then it asks me again the next time. Shouldn't it remember?

Should it remember? Is there a reason we chose to have it never record this preference? Is recording a preference itself a data privacy option that needs to be disclosed?

**Comment by brianwdavis** [comment]
@mikahpinegar thoughts?

**Comment by mikahpinegar** [comment]
start off by using local storage to remember analytics selection
