### ISSUE TITLE
Feedback API

### ISSUE THREAD

**Issue by trevorjpuckett** [precision-sustainable-ag/dst-selector#293]
## Overview

> Interactive Documentation: https://developfeedback.covercrop-data.org

The Feedback API provides an interface to create Github Issues in any repository in the `precision-sustainable-ag` company. 

This request will return a 201, with a `status` of 'failed' if the repository property is not a valid repository that already exists in the `precision-sustainable-ag` company.  When an issue fails to be created in Github, a Slack notification will be posted in the`failed-feedback-logs` channel.

## Endpoints

- `/v1/issues` - Creates an issue, and posts it to a repository in the `precision-sustainable-ag` company.

#### HTTP Request
> POST https://developfeedback.covercrop-data.org/v1/issues
##### payload
```json
{
  "repository": "dst-feedback", // make sure to check with Mikah / Brian / Adam to  verify which repo we want to post this to.
  "title": "string",
  "name": "string",
  "email": "string",
  "comments": "string",
  "labels": [
    "string" 
  ]
}
```

#### Ex. Response
```json
{
  "type": "string",
  "data": {
    "status": "success", // this will either be 'success' or 'failed' depending on the outcome of the request to Github.
    "payload": { // this is the issue saved in the database, to ensure no data loss in case of Github request failure.
      "id": 0,
      "repository": "string",
      "title": "string",
      "name": "string",
      "email": "string",
      "comments": "string",
      "labels": [
        "string"
      ]
    }
  }
}
```

#### Ex. Javascript Request
```javascript
const requestPayload = {
  "repository": "dst-feedback",
  "title": "Example Issue",
  "name": "John Doe",
  "email": "johndoe@example.com",
  "comments": "This is an example issue.",
  "labels": ["bug"]
};

fetch('https://developfeedback.covercrop-data.org/v1/issues', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(requestPayload)
})
  .then(response => response.json())
  .then(body => {
    if (body.data.status === 'success') {
      console.log('Feedback successfully sent to Github!');
      console.log(body.data.payload);
    } else {
      console.log('Failed to send Feedback to Github.');
    }
  })
  .catch(error => console.error(error));
```

**Comment by trevorjpuckett** [comment]
@ssharm1524  lmk if you need any additional information / help!

**Comment by brianwdavis** [comment]
Is there any kind of authentication on this endpoint?

**Comment by trevorjpuckett** [comment]
no, it is currently public.

**Comment by trevorjpuckett** [comment]
@brianwdavis I did build out the functionality in the dst-data-entry-auth-api to add public, domain controlled authorization for a service to service communication. it just is not currently implemented in the feedback api. I can probably add it in in about by EoD tomorrow and update this ticket if you would like?
