### ISSUE TITLE
cc-selector not forwarding routes

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#301]
https://covercrop-selector.org/species-selector works to route the front page and https://cc-selector.org/species-selector does not

**Comment by brianwdavis** [comment]
Completed on the cloudflare dashboard. The Forwarding URL rule under Page Rules needs to refer to the new URL with `covercrop-example.org/$1` when the original request is structured like `cc-example.org/*`. I'll complete this for the other tools after a few hours to make sure the settings propagated correctly.
