### ISSUE TITLE
add logic to only show NECCC on production site

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#302]
**What's wrong**
- we don't want to launch the new regions to production until the councils have had a chance to review and approve

**What done looks like**
- add an env variable to .env called `REACT_APP_ENVIRONMENT` and set it to development or production locally based on what you want to test. if `REACT_APP_ENVIRONMENT === 'production'`  then only show NECCC. if `REACT_APP_ENVIRONMENT === 'development'` then show all councils. i will update these env variables in the pipelines

**Where the changes need to be made**
- .env, multiple places

**Comment by Adamws33** [comment]
updated so only NECCC is avaliable on branch thumbnail_images.  filter and sorting updates in review on same PR
