### ISSUE TITLE
update crop data and crop data dictionary apis

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#303]
**What's wrong**
- selector is still using the static JSON data dictionary

**What done looks like**
- the cards for selector calendar view, list view, explorer and my crop list all need to be updated to use data from the new API
- data dictionary also needs to be updated with new API

**Where the changes need to be made**
- all over

**Comment by Adamws33** [comment]
Completed on branch thumbnail_images other updates in review on PR
