### ISSUE TITLE
Extract weather into Bit component

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/dst-selector#323]
**What's wrong**
- Code to query the weather API and show the current weather exists in this repo

**What done looks like**
- Extract that code into a reusable component in the https://github.com/precision-sustainable-ag/dst-bit-components repo

**Where the changes need to be made**
- TBD, @miladagreen should decide the folder structure in that repo

**Comment by mikahpinegar** [comment]
closing due to removing the weather widget
