### ISSUE TITLE
fix info bar styling

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#329]
**What's wrong**
- the break point for stacking the tabs on the info bar is way too big
- the info bar is using lots of <div> elements with bootstrap styling which we want to remove

**What done looks like**
- ideally the next, back, and restart buttons are all fixed on the right hand side of the green bar on larger screens
- the location, soil conditions, weather, and goals tabs should be dynamic and stack in a way that makes more sense depending on screen size
- on phone sized screens, stacking the  location, soil conditions, weather, and goals tabs is still fine
- all the bootstrap classes should be removed 

**Where the changes need to be made**
- /src/pages/Header/InfomationBar/InformationBar.js

**Comment by mikahpinegar** [comment]
here's the commit that i reverted to give you some ideas https://github.com/precision-sustainable-ag/dst-selector/commit/9af7c523a5b1db0f2f7190375dccf9ed775f7d51

**Comment by boscosylvester-john** [comment]
Changes completed and included in PR #330
