### ISSUE TITLE
move next button from landing page into the information bar

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#331]
**What's wrong**
- on the first page with the state selection map, the next button is at the bottom. this is confusing because when you click next, it moves to the information bar

**What done looks like**
- next button is moved into info bar
- next button stays disabled until a state is selected
- back and restart buttons should be disabled until a state is selected and the user has clicked next at least once

**Where the changes need to be made**
- Landing.js
- InformationBar.js

**Comment by boscosylvester-john** [comment]
Changes completed and included in PR https://github.com/precision-sustainable-ag/dst-selector/pull/332
