### ISSUE TITLE
favicon isn't region-appropriate

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/dst-selector#409]
**What's wrong**
- The favicon is currently hardcoded with the NECCC logo.

**What done looks like**
- Start the tool with the PSA logo as the favicon, then update it on region selection (or keep it as the PSA logo if that's not feasible)

![image-1~2](https://github.com/precision-sustainable-ag/dst-selector/assets/13338560/dbc051f8-672c-4aa6-a31c-f2651dd2200c)

**Comment by ameyachavan007** [comment]
do we have  a psa favicon in the repo?
