### ISSUE TITLE
cleanup unused redux state

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#423]
**What's wrong**
- a lot of redux state is unused or minimally used. this is a first cut of investigating unused state. this is based on a quick look through so when removing, please make sure that they can really be removed

**address slice**
- [x] remove addressVerified
- [x] remove addressChangedViaMap
- [x] remove fullAddress
- [x] the weather api calls should be made in Location.js and and zipCode should be moved out of redux and be local to Location only
- [x] remove zoneText
- [x] remove zoneId and all updateZone dispatch calls
- [x] remove lastZone
- [x] remove lastZipCode 

**crop slice**
- [x] move activeGrowthPeriod into local state for calendar view
- [x] remove snackOpen from crops slice, already exists in shared slice

**remove files**
- [x] remove store.js
- [x] remove reducer.js

**filters slice**
- [x] cropFiltersOpen should be local state in cropSidebar

**map slice**
- [x] remove regionLabel
- [x] remove regionShorthand
- [x] remove selectedRegion
- [x] remove council and add councilLabel, councilShorthand to default state

**goals slice**
- [x] remove allGoals 
- [x] goalsOpen should be local state in CoverCropGoals.js

**shared slice**
- [x] remove snackHorizontal and snackVertical because they are never updated, make local to App.js
- [x] investigate and hopefully remove dataDictionary
- [x] investigate speciesSelectorActivationFlag

**weather slice**
- [x] remove pondingFrequency
- [x] remove weatherDataReset

**soil slice**
- [ ] remove or do something with isSoilDataLoading
- [ ] remove or use isSoilDataLoading

**Comment by Adamws33** [comment]
address slice section on PR https://github.com/precision-sustainable-ag/dst-selector/pull/428

**Comment by Adamws33** [comment]
DataDict was moved into myCoverCropComparison component which was the only place it was being used.  and the speciesSelectorActivationFlag looks to be used in a few places and get set to both true and false in different places.
