### ISSUE TITLE
add fly free dates

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#464]
**What's wrong**
- selector needs to indicate the fly free date like the MCCC tool does
![fly free](https://github.com/precision-sustainable-ag/dst-selector/assets/55995241/6423753a-7af8-472b-aaaa-79817c8963da)

**What done looks like**
- diamond icon from MCCC tool should be shown on fly free date
- hover text should say `Plant after <date> to avoid Hessian flys"
- in planting and growth windows under `Hessian Fly Free Date`

**Where the changes need to be made**
- calendar view, list view

**Comment by mikahpinegar** [comment]
i will look for the icon

**Comment by mikahpinegar** [comment]
this is the code for adding the diamond icon to the svg from the MCCC tool

```
// Add fly free diamonds
    var diamondHeight = y.rangeBand()*0.9
    var diamondWidth = height*0.015
    var originalPos = [[0,1], [0.5,0.5], [0,0], [-0.5,0.5]]

    for(var j = 0; j < flyFreeDates.length; j++){
      var startDate = flyFreeDates[j].startDate
      var taskName = flyFreeDates[j].taskName
      if(startDate == undefined){
        continue
      }

      svg.append("polygon")
          .attr("points",`
            ${diamondWidth*originalPos[0][0]},${diamondHeight*originalPos[0][1]} 
            ${diamondWidth*originalPos[1][0]},${diamondHeight*originalPos[1][1]} 
            ${diamondWidth*originalPos[2][0]},${diamondHeight*originalPos[2][1]} 
            ${diamondWidth*originalPos[3][0]},${diamondHeight*originalPos[3][1]} 
            `)
          .attr("stroke","orange")
          .attr("fill","orange")
          .attr("stroke-width",1)
          .attr("transform",`translate(${x(startDate)},${y(taskName)})`)
          .attr("onmouseover", function(){
            return highlightBar(taskName, startDate)
          })
          .attr("onmouseleave", function(){
            return unhighlightBar(taskName, startDate)
          })
    
    }
```

**Comment by jinamshah** [comment]
Changes made to `constants.js` and `CropPaintGrowthChart.js`

Attached images of examples

![Image](https://github.com/precision-sustainable-ag/dst-selector/assets/40169508/215c4386-2b0f-4185-b9ae-18b548a3e664)
![Image](https://github.com/precision-sustainable-ag/dst-selector/assets/40169508/f048fb68-1914-4cfb-9d16-8e89b7d6cd7c)

**Comment by jinamshah** [comment]
Question: do we want to add a date range in the tooltip when there are multiple "conditions" in the planting and growth windows?
Attaching an example of the case.


![Image](https://github.com/precision-sustainable-ag/dst-selector/assets/40169508/96dfd79c-03c9-4fa8-be0a-bb64c53a15ce)
