### ISSUE TITLE
Front End Suggestions for Calendar View Header and button organization

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/dst-selector#480]
Suggestion for Moving "My List" Button from Top to above the Add to My List. 
This will 1) Remove awkward white space and 2) feel more intuitive for people who want to click My List header. This can remove it as a useless header. A red circle with a red "0" will prompt people to want to add to My List.
![image](https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/81be2557-5eed-4aca-8329-b1b5d7d31803)

Mock-up
![image](https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/fa172823-f89d-4b6f-a818-a8f25de53e8d)

**Comment by saseehav** [comment]
Move the sort by cover crop feature above the cover crops that they will be sorting instead of in the middle of the header.
![image](https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/fa70be0c-335c-4e77-8564-bc969c7d47b1)

![image](https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/4a530c51-a022-4647-8f9b-7f02961650d5)

**Comment by saseehav** [comment]
Add a button each "Calendar View" and "List View" that appear on both view pages, and when one is selected it is highlighted, so users can see there are 2 views and which one they are currently in. This will make it more intuitive that they can toggle back and forth. 
<img width="149" alt="image" src="https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/5b896351-542e-4cb8-8ee6-0d6ef6900b2a">

**Comment by saseehav** [comment]
Move the legend for the calendar view to directly above the calendar portion. make the "Cover Crop Growth Window" header smaller, longer and more lean across the months, and remove the whitespace above it. 

Currently: 
![image](https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/5eaf180c-f2ac-4a90-a4cf-5c3a5858608f)


Mock-up
![image](https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/cb1e1084-45bd-4c19-bfd3-b1071912b046)

**Comment by mikahpinegar** [comment]
@Adamws33 i'm assigning this issue to you. all that needs to be done is add a button in the sidebar so there is one for both calendar and list view and have whichever one you're on be highlighted. 

![buttons](https://github.com/precision-sustainable-ag/dst-selector/assets/55995241/e2f03c96-ff34-4fc6-bab9-3ac352fcb09b)

currently there is only one button and it switches the label based on which part of the tool you are using
