### ISSUE TITLE
Feedback in Selector Tool

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/dst-selector#482]
Is the feedback repository planning to collect feedback from all the tools ever? 
Is it private because it is coming in from a website? 
Should the feedback from each tool go to it's own repo? if no, can you create a tag from each tool?
Game Theory mentioned the Feedback button in the training and now I imagine that is where evaluators are going to want to click.

A user tried to use the feedback button on Oct 4th and became unresponsive.

This was what she wrote to me: "Two issues - Climate data seemed off and website froze;

 I put in my address in Ouachita Parish, LA and when it came to the Climate data, the numbers seemed wrong.  Avg precip for October was the same as Avg Annual Precip (which was higher than it should be); Avg Frost date first was too soon, and avg frost date last was too late.  Frost Free Days was too short.  I edited all that data. 

when I reached the page to put in cash crop, the page froze, became unresponsive and asked me to close the page.  Had to reload.  Once I did, it worked fine the rest of the way through.
Then, when I tried to give feedback, it would not let me submit it and gave me “internal server error” message."

https://github.com/precision-sustainable-ag/dst-feedback/issues

**Comment by mikahpinegar** [comment]
closing this issue since the feedback and precip inconsistencies have been fixed
