### ISSUE TITLE
How is the initial cc Output list sorted?

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/dst-selector#509]
How is the cover crop order output of the tool initially presented ? I cannot tell. It is not
1. Alphabetical
2. By grass first then legume
3. By goal
4. By growing window

I can't get the sort by cc name or goal to sort the cc by the initial way they are presented. If I were to tell a grower how the crops were presented to them in a particular order, what would I say?

**Comment by brianwdavis** [comment]
It looks like they're alphabetical, but sorted on the `label` field of the `/crops` endpoint response, e.g. "Alfalfa, Dormant". However, it's displayed on the front end as "Dormant Alfalfa", and subsequently sorting alphabetically uses this version of the name instead of the API version.
