### ISSUE TITLE
Padding on login modal is too much on mobile

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/dst-selector#510]
![Screenshot_20231107-160439](https://github.com/precision-sustainable-ag/dst-selector/assets/13338560/2aa5a222-1ab2-46d6-aba6-a30ac18e814f)

**Comment by YazidZidane** [comment]
Quick fix for this issue: In `AuthModal.js` change the style `maxWidth` to `minWidth` and set a proper value would solve this, some stylings could also be added to make it look better.
`ConsentModal.js` should also be changed since they are using the same styling.
