### ISSUE TITLE
update language in about and help for SCCC

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#515]
**What's wrong**
- some language should be generalized for all councils
- some language should be council specific

**What done looks like**
- send a document to @mikahpinegar with updated about and help text

**Comment by saseehav** [comment]
About Page

[ ]  History and Purpose of the NECCC Tool Effort

- Q:  Universal for all councils? Remove the 'NECCC' individual tool history and replace with a universal 4 council history and purpose, beginning with MCCC, moving to NECCC, then SCCC and WCCC. 

Script Idea: 

[ ] Cover Crop Data

- Q: Universal for all councils? Start with the most universal lines and move into 4 sections for each council, then a paragraph for data sources and data availability, copyright and license
- Q: Do we need a copyright and license section?

Script Idea:

[ ] Tool Design Process
- Q: Is this section necessary? I would love to see it cut or merged in part with the history. 
- could possibly be universal if we included the MCCC process and then testing efforts ongoing now with Game Theory

Script Idea:

[ ] Many Thanks to our Funders
- Universal on the about page for every one, all funding sources combined.

Script Idea:

[ ] Contact Us
- Q1: Universal for all councils and put into a feedback section? 
- Q2: Either A single email universal email address for all councils (covercropselector@psa.com) or a feedback form that populates that email and gets forwarded to all the program managers or long term contact in charge of tool maintenance long term? Or only the feedback button?

- [ ] About the Experts
- This is one of the most individual section, has experts per region. Could be a single list divided by councils.

**Comment by saseehav** [comment]
Help Page

- [ ] How to use the NECCC Species Selector Tool

- [ ] FAQ
- Looks universal to me
- [ ] Data Dictionary
- checking with @Victoria to see if this is universal for each council
- [ ] Information Sheets
- what is the point of this page? are we encouraging its use? what if it falls out of date? this is purely regional

**Comment by saseehav** [comment]
Notes from meeting 12/4/2023
1. Anna and Sarah don't think history necessary section. 
2. Can the help page only come up after the region is selected so the help videos are regional? like the browser. 
3. 4 sets of FAQ's and data dictionaries
4. Information Sheets should be called Additional Resources - think about aggregating all the information? Have a whole list and then divide it out by region in the page - why aren't the links hyperlinked and shortened?

Things that we can make universal: "Licensing and Acknowledgements" 
1. Cover crop data license and copyright
2. Acknowledgements Funding Sources
3. Additional Resources : Fact Sheets can be universal but regionally specific

Things that are regional:
1. Experts - for South it's in airtable. 
2. Help Videos
3. FAQs
5. Data Dictionaries - lives in airtable for each council. 

Ask where this regional part can come up on the page.

**Comment by saseehav** [comment]
Document with text for new About and Help Pages https://docs.google.com/document/d/1R9Di6VBoWS9ML9zZ2NdES60fp2tkSN0ti2fJdZD0N3c/edit#heading=h.5zhfsrqvv429

**Comment by Adamws33** [comment]
Update CSV for South with all Experts info so we can add into DB
