### ISSUE TITLE
verify that all cases in the reducer switch case are used

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#52]
- i suspect there are lots of unused pieces of state currently. we want to remove any cases that are unused and remove the data they touch in initialState
- resolved when unused cases and data are rmeoved

**Comment by Adamws33** [comment]
### Never used:
FALSE 
JUMP_SPECIES_PROGRESS
WEATHER_DATA_RESET
CHANGE_ADDRESS_BY_TYPING
UPDATE_LAST_ZONE
UPDATE_MARKER_COPY
UPDATE_ADDRESS_ON_MAP_CLICK
TOGGLE_ADDRESS_CHANGE_BUTTON
TOGGLE_CROP_DETAIL_MODAL
UPDATE_SELCTED_CHECKBOXES
UPDATE_ADDRESS_SEARCH_PREFERENCE
UPDATE_ACTIVE_GROWTH_PERIOD*

### Using Change:
TOGGLE
TRUE


### Using dispatch:
UPDATE_ACTIVE_CROP_DATA
LAST_ZIP_CODE
UPDATE_CONSENT
UPDATE_PROGRESS
UPDATE_LOCATION
UPDATE_ZONE_TEXT
CHANGE_ADDRESS
CHANGE_ADDRESS_VIA_MAP
RESET
UPDATE_MARKER
ADD_GOALS
SNACK
UPDATE_SELECTED_GOALS
ADD_SELECTED_GOALS
DRAG_GOALS
PULL_CROP_DATA
SELECTED_CROPS_MODIFIER
ACTIVATE_MY_COVER_CROP_LIST_TILE
ACTIVATE_SPECIES_SELECTOR_TILE
UPDATE_WEATHER_CONDITIONS
UPDATE_FROST_FREE_DAYS
UPDATE_AVERAGE_FROST_DATES
UPDATE_AVERAGE_PRECIP_CURRENT_MONTH
UPDATE_AVERAGE_PRECIP_ANNUAL
SET_AJAX_IN_PROGRESS
TOGGLE_SOIL_LOADER
UPDATE_SOIL_DATA
UPDATE_SOIL_DATA_ORIGINAL
UPDATE_DATE_RANGE
UPDATE_ZIP_CODE
UPDATE_DRAINAGE_CLASS
UPDATE_FLOODING_FREQUENCY
UPDATE_COMPARISON_KEYS


### Both change and dispatch:
UPDATE_ZONE

**Comment by Adamws33** [comment]
How do change and dispatch differ? they seem to be the same so we should eliminate using the other.

**Comment by mikahpinegar** [comment]
all change does is pass in the new state differently depending on if it's an object or not. that could easily be eliminated but might take a bit of refactoring. did i understand the notes above correctly that change is only used for 3 pieces of state?

**Comment by Adamws33** [comment]
Yes i believe so.  i may have missed a few but there was very little using change compared to dispatch.  I didn't start keeping track of which were using change till a little later.  I actually meant to omit that piece of info because i wasn't sure how complete it was.
