### ISSUE TITLE
migrate application to use redux

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#53]
- currently the crop data and data dictionaries for each zone are stored using useReducer which causes a lot of unneeded renders
- resolved when global state is stored using redux

**Comment by Adamws33** [comment]
### Unused State
addressSearchPreference: 'address',
markersCopy: [],
showAddressChangeBtn: false,
selectedCheckboxes: [],
selectedStars: {},
zoom: 13,
addressVerified: false,
modalOpen: false
modalSize: 'lg', //sm,md,lg,fluid
modalBody: {},
addToCartBtnText: 'add to list',
soilData.Ponding_Frequency: '',
cropDetailModal: false,
greenbarExpanded: false,
isSoilDataLoading: false,
cashCropData.name: '',

### Only used in one place.
addressChangedViaMap - GoogleAutocomplete.js
fullAddress - GoogleAutocomplete.js
zip - Header.js
zipCode - Header.js
lastZipCode - Header.js
allGoals - GoalsSelector.js
snackOpen - app.js
snackVertical - app.js
snackHorizontal - app.js
snackMessage - app.js
zoneToggle - cropSidebar.js
state.soilDataOriginal - Reducer.js ***
soilData.Map_Unit_Name - Greenbar.js
the weatherData object info needs to be revewed

### crop-data.js that arent used anywhere (zone 7)
Standard Fall/Winter Seeding Rate Date End
Late Fall/Winter Seeding Rate Date Start
Standard Fall/Winter Seeding Rate Date Start
ITIS TSN

### Only in JSON objects
Notes: Environmental Tolerances
