### ISSUE TITLE
update flooding options for MCCC and make it filter crops

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#531]
**What's wrong**
- What is the feature or hotfix that needs to be created/fixed.  
- Why this is causing issues

**What done looks like**
- How things will be working once the ticket is completed.
- A list of noticeable changes that are expected from the ticket
- Any details in how changes are expected to look and act

**Where the changes need to be made**
- The file name where the bug is located
- What part of the application the feature should be added to (Adding in a file name if its not a new component)
- A list of known file names that are affected by an application wide change

**Comment by Adamws33** [comment]
Pull flooding options from the backend?

**Comment by mikahpinegar** [comment]
trevor has an endpoint that will return all of the options that are in use for an attribute for a specific set of regions. example call below

`{{selector_service_url}}/v2/attribute?label=flooding frequency&regions=17&regions=76`

it contains a list of display label and value pairs that will be used for filtering. all of the possible labels should be mapped over and displayed on the front end. the corresponding values should be used to filter down the crops
