### ISSUE TITLE
Remove species rate recommendations 

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/dst-selector#543]
With the launch of the seeding rate calculator, and updated rate recommendations, should we delete the information regarding seeding rates from the selector tool.

**Comment by mikahpinegar** [comment]
yeah or at least have it just link to the seeding rate calculator. which would you prefer?

**Comment by saseehav** [comment]
The council managers would like keep seeding rates in the species selector instead of referring people to the calculator directly. The data will just have to come out of the most up-to-date table in the seeding rate calculator.

**Comment by mikahpinegar** [comment]
can this issue be closed?

**Comment by saseehav** [comment]
Yes, if you create a new issue to move the seed rates from the calculator
into the selector tool

**Comment by mikahpinegar** [comment]
i'm looking back into this issue and i'm not sure i'm following. that information is already in airtable and ingested into the api. you're talking about this right? 

![seeding rates](https://github.com/precision-sustainable-ag/dst-selector/assets/55995241/0ad4829a-4ba1-4be5-86d7-07b7303615d2)

is this information not accurate to what's in the seeding rate calculator's airtable data?

**Comment by saseehav** [comment]
The seeding rate calc airtable has new, updated rates, that may conflictb
with these rates.

**Comment by mikahpinegar** [comment]
after thinking about it some more, the process for updating this data should be for victoria and/or the experts to update the values in airtable and then request a data pull from us. we have no way of knowing which rates are applicable to which tool. airtable is the source of truth for what gets displayed in the tools and it doesn't make sense for the developers to ever edit those values

**Comment by mikahpinegar** [comment]
the data will be updated in airtable by the experts and then pulled into the database once completed
