### ISSUE TITLE
items with multiple values aren't on the info sheet and only showing the first item

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#555]
**What's wrong**
- ex soil drainage has multiple values. it's only showing the first item on the info sheet

**What done looks like**
- items should be mapped and joined by commas

**Where the changes need to be made**
- informationsheetcontent.js

**Comment by ameyachavan007** [comment]
![Screen Shot 2024-02-12 at 18 35 43](https://github.com/precision-sustainable-ag/dst-selector/assets/55220837/6623d6aa-1dc5-407b-b350-b16affa56a54)


I am able to show different values for an attribute, any suggestions for UI changes?

**Comment by mikahpinegar** [comment]
i think this design takes up too much space. what does it look like just concatenating them with commas? or putting them into a grid without the styling?
