### ISSUE TITLE
Cover Crop Pictures missing 

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/dst-selector#583]
**What's wrong**
-The cover crop images for some species are missing (greyed out thumbnails) from the output of the recommendation
<img width="547" alt="image" src="https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/4bab46db-995e-4b0c-a99e-419f33050529">

**What done looks like**
- Victoria should finish gathering or getting the remaining images. If none are present, select from other regions. If other regions don't have them, find on the internet. 
- Let us know where images are and when that is complete. 

**Where the changes need to be made**

**Comment by mikahpinegar** [comment]
we're already using other regions images if they exist. the only images that are grayed out have no image for any region

**Comment by saseehav** [comment]
still missing some images in the SCCC
<img width="413" alt="image" src="https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/9cfc945e-2134-45d7-b249-df634f9e61d3">
