### ISSUE TITLE
Need Source Data on cover crop images

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/dst-selector#586]
**What's wrong**
- There is text under the carousel of images in the cover crop information sheet that says "Need Source Data". What is that?

<img width="316" alt="image" src="https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/27db2d87-025f-4c31-95e2-d3430e27b78e">

**Comment by mikahpinegar** [comment]
that signifies that an image doesn't have an author listed in the api

**Comment by mikahpinegar** [comment]
this was actually displaying on all images in error. i just linked a pr to this issue to resolve it
