### ISSUE TITLE
CropTable Ternery cleanup

### ISSUE THREAD

**Issue by Adamws33** [precision-sustainable-ag/dst-selector#68]
This issue is located in the CropTable.js and will require the whole file to be reviewed

**Current Issue:** this file and the whole application really is full of poorly written ternary operators.  some examples are below.  Please search through all of the ternary operators in this file and look to simplify them.  

**Completed When:** when there are no operators matching any of the examples below.  

**Stretch Goal:** since this component has not yet been refactored I could use some guidance where we can find components (like legend) that can be broken out.  Its ok if these components aren't used anywhere else we want to break our code into smaller easier to read and understand components.  
Please leave comments her with line numbers/referencing const names etc and how you think it can be refactored.  

Ex. 
a ternary should never have a null or empty 

variable ? <Component /> : " "
variable ? <Component /> :  null

this ternary is at the wrong scope we see similar info on both sides of the : we should be looking to simplify that. 
style = {
  variable ? 
    { backgroundColor: white }
  :
    { backgroundColor: blue}

**Comment by dearpriyankasa** [comment]
Hi @Adamws33 ,
The PR related to this issue could be found here - https://github.com/precision-sustainable-ag/dst-selector/pull/78
