### ISSUE TITLE
move json objects to azure

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#77]
**What's wrong**
json objects are stored in the repo

**What done looks like**
json objects stored in blob storage

**Where the changes need to be made**
azure, src/shared/images

**Comment by brianwdavis** [comment]
Is this the right flow? or is it better to use a datastore like a managed Mongo and pgsql instance and then just purge the repo of these objects? Blob storage and API seems like an intermediate step that we won't use for long.

**Comment by mikahpinegar** [comment]
yeah it is definitely a short term solution. we still want to move everything into a db and build an api around it. drew just mentioned that when moving all the images to blob storage it would be easy to just plop the json there as well so we can get the repo cleaned up from all the unneeded files

**Comment by mikahpinegar** [comment]
but we wouldn't even need to make an api around the json objects in blob storage, just download it directly and use it how it's currently being used
