### ISSUE TITLE
Refactor DST selector

### ISSUE THREAD

**Issue by Adamws33** [precision-sustainable-ag/dst-selector#83]
These files need refactored - once done please leave a comment with the file name once done

**To Do**
Header (625) - Priyanka
WeatherCondition (690) - Priyanka
MyCoverCropComparisonComponent (497)

**Done**
CropCalendarView (625) - Aaron 
CropTable (757) - priyanka
InformationSheetContent (1074) & informationSheet - priyanka
SoilCondition (625) - priyanka
Greenbar (401) now named InformationBar - Adam
Location.js - Adam

Secondary
ForcastComponent - review how return is handled and set .then() var to res.

**Comment by dearpriyankasa** [comment]
Have refactored CropTable (757) file

**Comment by Adamws33** [comment]
When refactoring informationSheetContent please also refactor informationSheet.  InformationSheet uses crop as a variable in 3 different ways at different places.  this should not be done and needs to be refactored and tested to have different variable names to go with what they are doing.

**Comment by Adamws33** [comment]
InformationBar AKA Greenbar has some logic that allows you to update some of the items chooses in setting up the selector tool.  These items extend the informationBar and make a large bar for editing if we can i think we should pull these out and update them with a Modal.

**Comment by dearpriyankasa** [comment]
Have refactored the header component files. Review PRs related to issue - https://github.com/precision-sustainable-ag/dst-selector/issues/139
