### ISSUE TITLE
choose api framework and db

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#95]
**What's wrong**
the selector currently has no API or DB and is using static JSON objects to build out the front end. we want to migrate this to use an API and DB and the first step will be choosing the architecture for the project. we discussed Node.js, Express.js, and PostgreSQL. if this is the final decision you can close this ticket once a document is created in confluence going over the design choices

**What done looks like**
- a choice is made about what language and frameworks to use for the API
- a choice is made about what database to use
- these choices are documented in confluence

**Where the changes need to be made**
confluence

**Comment by trevorjpuckett** [comment]
Proposed Architecture document is done! Link is below.

https://precision-sustainable-ag.atlassian.net/wiki/spaces/DST/pages/172883969/Proposed+Architecture
