### ISSUE TITLE
research JSON objects and begin thinking about DB table structure

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#97]
**What's wrong**
once DB selection is made, we'll need to figure out the best way to migrate the JSON objects into the new DB. to do this we'll need to make a database diagram to figure out what tables and relations will be needed

**What done looks like**
- database diagram for the new DB in confluence

**Where the changes need to be made**
the JSON objects are linked below
- https://github.com/precision-sustainable-ag/dst-selector/tree/feature/json/src/shared/json

**Comment by mikahpinegar** [comment]
i just realized there's another json object at src\components\InformationSheet\sources.json that's used to list sources on the information sheet. this will need to get added to the DB as well

**Comment by trevorjpuckett** [comment]
Thanks Mikah! I definitely would have missed that! I will check it out before our meeting at 2pm!

**Comment by trevorjpuckett** [comment]
Database diagram can be found here: https://precision-sustainable-ag.atlassian.net/wiki/spaces/DST/pages/172883969/Proposed+Architecture
